create seat_sheet and seat_pair #21
youngeek-0410/SekigaeService pull request #182
Opened 2021-09-03 05:14 UTC by is-hoku

# 概要

seat_sheetとseat_pairのモデルを追加

# 対応するIssue

close #21

# 修正内容の確認方法

# レビューのポイント

# 備考

2021-09-03 08:19 UTC, kathmandu777 requested changes
ForeignKeyのところはnotionとは少し異なるけどレビューのほうを参考にして再実装してください。
あと、migration fileがないのでローカルでmigrationをして作成してください。

2021-09-03 08:19 UTC, kathmandu777 commented on django/sekigae/models/seat_pair.py
> +        return self.seat_id
SeatPairは学生と座席のつながりを意味しています。もう少しわかりやすい表示にしましょう。

2021-09-03 08:19 UTC, kathmandu777 commented on django/sekigae/models/seat_pair.py
> +class SeatPair(models.Model):
こっちにもTimeStamp継承させてほしい

2021-09-03 08:19 UTC, kathmandu777 commented on django/sekigae/models/seat_sheet.py
> +    updated_at = models.DateTimeField(default=timezone.now)
Timestampを継承しているので不要です。

2021-09-03 08:19 UTC, kathmandu777 commented on django/sekigae/models/seat_pair.py
> +    seat_id = models.ForeignKey(Seat, on_delete=models.CASCADE)
seat_id -> seat

2021-09-03 08:19 UTC, kathmandu777 commented on django/sekigae/models/seat_pair.py
> +    student_id = models.ForeignKey(Student, on_delete=models.CASCADE)
student_id -> student

2021-09-03 08:19 UTC, kathmandu777 commented on django/sekigae/models/seat_pair.py
> +    seat_sheet_id = models.ForeignKey(SeatSheet, on_delete=models.CASCADE)
ditto

2021-09-03 08:19 UTC, kathmandu777 commented on django/sekigae/models/seat_sheet.py
> +    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
user_id -> owner

2021-09-03 08:19 UTC, kathmandu777 commented on django/sekigae/models/seat_sheet.py
> +                fields=["number", "user_id"],
numberはどっから出てきた？

2021-09-03 08:55 UTC, is-hoku commented on django/sekigae/models/seat_sheet.py
> +                fields=["number", "user_id"],
nameの間違いだった

2021-09-10 12:32 UTC, kathmandu777 requested changes

2021-09-10 12:32 UTC, kathmandu777 commented on Pipfile
> +python_version = "3.9"
いらないです
gitignoreよろしくです

2021-09-10 12:32 UTC, kathmandu777 commented on Pipfile.lock
> +{
pipfile.lockもいらないです

2021-09-10 12:32 UTC, kathmandu777 commented on django/sekigae/models/seat_sheet.py
> +                fields=["name", "user_id"],
user_idで動いている？
owner_idでは？モデル作成してみてエラー出ないか確認してください。

2021-09-16 17:39 UTC, is-hoku commented on django/sekigae/models/seat_sheet.py
> +                fields=["name", "user_id"],
変更してモデル作成できた

2021-09-16 17:40 UTC, is-hoku commented on Pipfile
> +python_version = "3.9"
気づかずトラックされてた、消した。

2021-09-17 22:20 UTC, kathmandu777 commented
@is-hoku 
assigneeに自分を追加してねー

2021-09-17 22:48 UTC, kathmandu777 reviewed
# commit単位について
```
fix some variables #21
create seat_sheet and seat_pair #21
```
は同じコミットにまとめてあったほうがいいね
```
ignore pipfile and rename a field #21
```
はpipfile ignoreは別で切り出して、rename fieldは前のコミットにまとめたほうが良いね

次回からcommit単位も考えてPR出してくれるとありがたい！今回はこれでOK。

# migrationファイルがない
モデルを作成したときはmigrationして、それで生成されたファイルもcommitしてください。

# __init__.pyに作成したモデルを追加する
sekigae/models/__init__.pyに追加してください。他ファイルからimportが楽になります。

こちらで修正対応引き受けます。

2021-09-17 22:48 UTC, kathmandu777 commented on django/sekigae/models/seat_sheet.py
> +    owner = models.ForeignKey(User, on_delete=models.CASCADE)
get_user_model()を使うようにする

2021-09-17 22:48 UTC, kathmandu777 commented on django/sekigae/models/seat_pair.py
> +    seat_sheet = models.ForeignKey(SeatSheet, on_delete=models.CASCADE)
https://itc.tokyo/2021/04/21/2013/
文字列で指定しましょう！import省けます。
メモ：以前のファイルも文字列にして全体をそろえsる

2021-09-17 22:51 UTC, kathmandu777 commented
adminページ用のファイルもないな
どうやって検証したんだ？
コマンド直打ち？
まあそれでもいいけどadminからやったほうが楽だと思うし、adminページは必要なので作成すること。

2021-09-17 23:32 UTC, kathmandu777 approved these changes
pipfileをignoreした履歴が混ざってるけどまあ許容

2021-09-17 23:32 UTC, merged